user www-data;
worker_processes auto;
error_log stderr;
pid /run/nginx.pid;

include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    map $http_x_forwarded_host $request_host_header {
        "" $http_host;
        default $http_x_forwarded_host;
    }

    map $request_host_header $qgis_host {
        "~(?<h>[^:]+)" $h;
        default $host;
    }

    map $http_host $port {
        "~*.*:(?<p>.*)" $p;
        default $server_port;
    }

    map $http_x_forwarded_proto $qgis_ssl {
        "https" "on";
        default $https;
    }

    map $http_x_forwarded_port $qgis_port {
        "" $port;
        default $http_x_forwarded_port;
    }

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name localhost 127.0.0.1;
        root /usr/share/nginx/html;

        location ~ ^/ows/([^/]+)/?$ {
            set $project_key $1;
            fastcgi_pass localhost:9993;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/data/qgis/qgis_mapserv.fcgi;
            fastcgi_param SCRIPT_NAME /ows/$project_key;
            fastcgi_param PATH_INFO "";
            fastcgi_param QGIS_PROJECT_FILE /io/data/published/projects/$project_key.qgs;
            fastcgi_param QGIS_SERVER_SERVICE_URL http://$request_host_header/ows/$project_key/;
            fastcgi_param QGIS_SERVER_WMS_SERVICE_URL http://$request_host_header/ows/$project_key/;
            fastcgi_param QGIS_SERVER_WFS_SERVICE_URL http://$request_host_header/ows/$project_key/;
            fastcgi_param HTTP_X_QGIS_SERVICE_URL http://$http_host/ows/$project_key/;
            fastcgi_param HTTP_X_FORWARDED_HOST $request_host_header;
            fastcgi_param HTTP_X_FORWARDED_PORT $qgis_port;
            fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
            fastcgi_param QUERY_STRING $query_string;
            fastcgi_param REQUEST_URI $request_uri;
            fastcgi_param HTTP_HOST $request_host_header;
            fastcgi_param HTTPS $qgis_ssl;
            fastcgi_param SERVER_NAME $qgis_host;
            fastcgi_param SERVER_PORT $qgis_port;
        }

        location ~ ^/ogc/([^/]+)(/.*)?$ {
            set $project_key $1;
            set $path_info $2;
            fastcgi_pass localhost:9993;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/data/qgis/qgis_mapserv.fcgi;
            fastcgi_param SCRIPT_NAME /ogc/$project_key;
            fastcgi_param PATH_INFO $path_info;
            fastcgi_param QGIS_PROJECT_FILE /io/data/published/projects/$project_key.qgs;
            fastcgi_param QGIS_SERVER_SERVICE_URL http://$request_host_header/ogc/$project_key/ogcapi;
            fastcgi_param HTTP_X_QGIS_SERVICE_URL http://$http_host/ogc/$project_key/ogcapi;
            fastcgi_param HTTP_X_FORWARDED_HOST $request_host_header;
            fastcgi_param HTTP_X_FORWARDED_PORT $qgis_port;
            fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
            fastcgi_param QUERY_STRING $query_string;
            fastcgi_param REQUEST_URI $request_uri;
            fastcgi_param HTTP_HOST $request_host_header;
            fastcgi_param HTTPS $qgis_ssl;
            fastcgi_param SERVER_NAME $qgis_host;
            fastcgi_param SERVER_PORT $qgis_port;
        }

        error_page 404 /404.html;
        location = /40x.html {}

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {}
    }
}
