services:
  api:
    build:
      context: ../..
      dockerfile: infra/docker/api/Dockerfile
    env_file:
      - ../../.env
    environment:
      WORKSPACE_ROOT: /app
      APP_BASE_URL: http://localhost:8000
      WEB_BASE_URL: http://localhost:5173
      DATA_DIR: ./data
      QGIS_SERVER_BASE_URL: http://localhost:8080
      QGIS_SERVER_INTERNAL_BASE_URL: http://qgis-server
      QGIS_MODELS_DIR: ./qgis/models
      QGIS_PUBLISH_DIR: ./qgis/published
      QGIS_RUNTIME_BASE_URL: http://qgis-runtime:8090
      DATABASE_URL: postgresql://geo_agent:geo_agent@postgis:5432/geo_agent
    ports:
      - "8000:8000"
    volumes:
      - ../../data:/app/data
      - ../../qgis:/app/qgis
    depends_on:
      - postgis
      - qgis-runtime
      - qgis-server

  qgis-runtime:
    build:
      context: ../..
      dockerfile: infra/docker/qgis-runtime/Dockerfile
    env_file:
      - ../../.env
    environment:
      WORKSPACE_ROOT: /app
      DATA_DIR: ./data
      QGIS_MODELS_DIR: ./qgis/models
      QGIS_PUBLISH_DIR: ./qgis/published
      QGIS_PROCESS_BIN: qgis_process
    ports:
      - "8090:8090"
    volumes:
      - ../../data:/app/data
      - ../../qgis:/app/qgis

  worker:
    build:
      context: ../..
      dockerfile: infra/docker/worker/Dockerfile
    env_file:
      - ../../.env
    volumes:
      - ../../data:/app/data
      - ../../qgis:/app/qgis
    environment:
      DATABASE_URL: postgresql://geo_agent:geo_agent@postgis:5432/geo_agent
    depends_on:
      - api

  postgis:
    image: postgis/postgis:16-3.5
    environment:
      POSTGRES_DB: geo_agent
      POSTGRES_USER: geo_agent
      POSTGRES_PASSWORD: geo_agent
    ports:
      - "5432:5432"
    volumes:
      - ../../infra/migrations:/docker-entrypoint-initdb.d

  qgis-server:
    image: qgis/qgis-server:latest
    ports:
      - "8080:80"
    volumes:
      - ../../qgis:/io/data
      - ../docker/qgis-server/nginx.conf:/etc/nginx/nginx.conf:ro
