// +-------------------------------------------------------------------------
//
//   地理智能平台 - PostGIS 图层检索工具
//
//   文件:       layerList.ts
//
//   日期:       2026年06月24日
//   作者:       OpenAI Codex
// --------------------------------------------------------------------------

import type { ToolDef } from '../../framework/types.js'
import type { PostGisRepository } from '../../gis/postgis.js'
import type { LayerDescriptor } from '../../schemas/types.js'
import { makeId } from '../../utils/ids.js'

// list_layers 是 Agent 进入平台图层事实源的只读入口。
// 它只返回 PostGIS 中已经注册的系统/会话图层，不做外部搜索或隐式导入。
export function createLayerListTool(postgis: PostGisRepository): ToolDef {
  return {
    name: 'list_layers',
    label: '检索平台图层',
    description: '按名称、分类、标签或来源检索平台中已经注册的 PostGIS 图层，不会访问外部数据源；行政边界查询不会返回自动生成的分析矩形。',
    group: '空间分析',
    tags: ['layer', 'postgis', 'catalog'],
    isReadOnly: true,
    isDestructive: false,
    jsonSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: '图层名称、描述或标签关键词，例如“杭州 行政区划”' },
        category: { type: 'string', description: '图层分类过滤' },
        sourceType: { type: 'string', description: '图层来源过滤，例如 system、analysis、upload' },
        status: { type: 'string', description: '图层状态过滤，默认 active' },
        limit: { type: 'integer', minimum: 1, maximum: 100, default: 20, description: '返回数量上限' },
      },
    },
    async handler(args, ctx) {
      const layers = await postgis.listLayers(ctx.sessionId, ctx.threadId)
      const queryTerms = normalizeQueryTerms(args.query)
      const entityTerms = extractEntityTerms(queryTerms)
      const boundaryIntent = hasAdministrativeBoundaryIntent(queryTerms)
      const category = optionalText(args.category)
      const sourceType = optionalText(args.sourceType)
      const status = optionalText(args.status) ?? 'active'
      const limit = boundedLimit(args.limit)
      const matches = layers
        .filter(layer => layer.status === status)
        .filter(layer => !category || layer.category === category)
        .filter(layer => !sourceType || layer.sourceType === sourceType)
        .filter(layer => !boundaryIntent || !isAutoGeneratedAnalysisLayer(layer))
        .filter(layer => entityTerms.length === 0 || entityTerms.some(term => searchableText(layer).includes(term)))
        .map(layer => ({ layer, score: queryScore(layer, queryTerms) }))
        .filter(candidate => queryTerms.length === 0 || candidate.score > 0)
        .sort((a, b) => b.score - a.score)
        .slice(0, limit)
        .map(candidate => publicLayerSummary(candidate.layer))

      return {
        message: matches.length
          ? `找到 ${matches.length} 个已注册图层`
          : '没有找到匹配的已注册图层',
        payload: {
          query: typeof args.query === 'string' ? args.query : null,
          count: matches.length,
          layers: matches,
        },
        warnings: [],
        resultId: makeId('result'),
        source: 'postgis',
        provenance: {
          backend: 'postgis',
          sessionId: ctx.sessionId,
          threadId: ctx.threadId,
          externalFetch: false,
        },
      }
    },
  }
}

function normalizeQueryTerms(value: unknown): string[] {
  if (typeof value !== 'string') return []
  const terms = value
    .split(/[\s,，、]+/u)
    .map(term => term.trim().toLowerCase())
    .filter(Boolean)
  const expanded = new Set(terms)
  for (const term of terms) {
    if (term.includes('杭州')) {
      expanded.add('杭州')
      expanded.add('杭州市')
    }
    if (term.includes('行政区划') || term.includes('区划')) {
      expanded.add('行政区')
      expanded.add('边界')
      expanded.add('区县')
    }
  }
  return [...expanded]
}

function extractEntityTerms(terms: string[]): string[] {
  const entities = new Set<string>()
  for (const term of terms) {
    const compact = term
      .replaceAll('行政区划', '')
      .replaceAll('行政区', '')
      .replaceAll('区划', '')
      .replaceAll('边界', '')
      .replaceAll('区县', '')
      .replaceAll('图层', '')
      .replaceAll('范围', '')
      .trim()
    if (compact) entities.add(compact)
  }
  return [...entities]
}

function optionalText(value: unknown): string | null {
  return typeof value === 'string' && value.trim() ? value.trim() : null
}

function boundedLimit(value: unknown): number {
  if (typeof value !== 'number' || !Number.isInteger(value)) return 20
  return Math.min(100, Math.max(1, value))
}

function searchableText(layer: LayerDescriptor): string {
  return [
    layer.layerKey,
    layer.name,
    layer.description,
    layer.category,
    layer.sourceType,
    layer.geometryType,
    ...layer.tags,
    ...layer.analysisCapabilities,
    ...layer.propertySchema.map(property => `${property.name} ${property.dataType} ${property.sampleValues.join(' ')}`),
  ].join(' ').toLowerCase()
}

function queryScore(layer: LayerDescriptor, terms: string[]): number {
  if (!terms.length) return 0
  const text = searchableText(layer)
  return terms.reduce((score, term) => score + (text.includes(term) ? 1 : 0), 0)
}

function hasAdministrativeBoundaryIntent(terms: string[]): boolean {
  return terms.some(term => ['行政区划', '行政区', '边界', '区县'].some(keyword => term.includes(keyword)))
}

function isAutoGeneratedAnalysisLayer(layer: LayerDescriptor): boolean {
  return layer.sourceType === 'analysis' && layer.tags.includes('auto-generated')
}

function publicLayerSummary(layer: LayerDescriptor): Record<string, unknown> {
  return {
    layerKey: layer.layerKey,
    name: layer.name,
    description: layer.description,
    sourceType: layer.sourceType,
    category: layer.category,
    status: layer.status,
    geometryType: layer.geometryType,
    featureCount: layer.featureCount,
    bounds: layer.bounds,
    tags: layer.tags,
    propertySchema: layer.propertySchema,
    analysisCapabilities: layer.analysisCapabilities,
    sessionId: layer.sessionId,
    threadId: layer.threadId,
    updatedAt: layer.updatedAt,
  }
}
